/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContaIndexRouteImport } from './routes/_authenticated/conta.index'
import { Route as AuthenticatedContaEnderecosRouteImport } from './routes/_authenticated/conta.enderecos'
import { Route as AuthenticatedContaPedidosIndexRouteImport } from './routes/_authenticated/conta.pedidos.index'
import { Route as AuthenticatedContaPedidosIdRouteImport } from './routes/_authenticated/conta.pedidos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaIndexRoute = AuthenticatedContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaEnderecosRoute =
  AuthenticatedContaEnderecosRouteImport.update({
    id: '/conta/enderecos',
    path: '/conta/enderecos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContaPedidosIndexRoute =
  AuthenticatedContaPedidosIndexRouteImport.update({
    id: '/conta/pedidos/',
    path: '/conta/pedidos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContaPedidosIdRoute =
  AuthenticatedContaPedidosIdRouteImport.update({
    id: '/conta/pedidos/$id',
    path: '/conta/pedidos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/conta/': typeof AuthenticatedContaIndexRoute
  '/conta/pedidos/$id': typeof AuthenticatedContaPedidosIdRoute
  '/conta/pedidos/': typeof AuthenticatedContaPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/conta': typeof AuthenticatedContaIndexRoute
  '/conta/pedidos/$id': typeof AuthenticatedContaPedidosIdRoute
  '/conta/pedidos': typeof AuthenticatedContaPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/_authenticated/conta/': typeof AuthenticatedContaIndexRoute
  '/_authenticated/conta/pedidos/$id': typeof AuthenticatedContaPedidosIdRoute
  '/_authenticated/conta/pedidos/': typeof AuthenticatedContaPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/loja'
    | '/painel'
    | '/reset-password'
    | '/admin'
    | '/produto/$slug'
    | '/conta/enderecos'
    | '/conta/'
    | '/conta/pedidos/$id'
    | '/conta/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/loja'
    | '/painel'
    | '/reset-password'
    | '/admin'
    | '/produto/$slug'
    | '/conta/enderecos'
    | '/conta'
    | '/conta/pedidos/$id'
    | '/conta/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/loja'
    | '/painel'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/produto/$slug'
    | '/_authenticated/conta/enderecos'
    | '/_authenticated/conta/'
    | '/_authenticated/conta/pedidos/$id'
    | '/_authenticated/conta/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LojaRoute: typeof LojaRoute
  PainelRoute: typeof PainelRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta/': {
      id: '/_authenticated/conta/'
      path: '/conta'
      fullPath: '/conta/'
      preLoaderRoute: typeof AuthenticatedContaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta/enderecos': {
      id: '/_authenticated/conta/enderecos'
      path: '/conta/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof AuthenticatedContaEnderecosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta/pedidos/': {
      id: '/_authenticated/conta/pedidos/'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos/'
      preLoaderRoute: typeof AuthenticatedContaPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta/pedidos/$id': {
      id: '/_authenticated/conta/pedidos/$id'
      path: '/conta/pedidos/$id'
      fullPath: '/conta/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedContaPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContaEnderecosRoute: typeof AuthenticatedContaEnderecosRoute
  AuthenticatedContaIndexRoute: typeof AuthenticatedContaIndexRoute
  AuthenticatedContaPedidosIdRoute: typeof AuthenticatedContaPedidosIdRoute
  AuthenticatedContaPedidosIndexRoute: typeof AuthenticatedContaPedidosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContaEnderecosRoute: AuthenticatedContaEnderecosRoute,
  AuthenticatedContaIndexRoute: AuthenticatedContaIndexRoute,
  AuthenticatedContaPedidosIdRoute: AuthenticatedContaPedidosIdRoute,
  AuthenticatedContaPedidosIndexRoute: AuthenticatedContaPedidosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LojaRoute: LojaRoute,
  PainelRoute: PainelRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
